import cv2
video_capture = cv2.VideoCapture(0)

while video_capture.isOpened():
    ret, frame = video_capture.read()
    print(video_capture.get(cv2.CAP_PROP_FRAME_WIDTH))
    print(video_capture.get(cv2.CAP_PROP_FRAME_HEIGHT))
    # gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    cv2.imshow('Video', frame)
    # cv2.imshow('Video', gray)

    if cv2.waitKey(1) == ord('q'):
        break
video_capture.release()
cv2.destroyAllWindows()
    # ret is True if the frame is read correctly, otherwise it is False
    # frame is the frame that is read
    # frame is a numpy array
    # print(ret)
    # print(frame)
    # print(type(frame))
    # print(frame.shape)
    # print(frame.ndim)
    # print(frame.size)
    # print(frame.dtype)
    # print(frame.item(0, 0, 0))
    # print(frame.item(0, 0, 1))
    # print(frame.item(0, 0, 2))
    # print(frame.item(0, 0, 3))
    # print(frame.item(0, 0, 4))
    # print(frame.item(0, 0, 5))
    # print(frame.item(0, 0, 6))
    # print(frame.item(0, 0, 7))
    # print(frame.item(0, 0, 8))
    # print(frame.item(0, 0, 9))
    # print(frame.item(0, 0, 10))
    # print(frame.item(0, 0, 11))
    # print(frame.item(0, 0, 12))
    # print(frame.item(0, 0, 13))
    # print(frame.item(0, 0, 14))
    # print(frame.item(0, 0, 15))
    # print(frame.item(0, 0, 16))
    # print(frame.item(0, 0, 17))
    # print(frame.item(0, 0, 18))
    # print(frame.item(0, 0, 19))
    # print(frame.item(0, 0, 20))
    # print(frame.item(0, 0, 21))
    # print(frame.item(0, 0, 22))
    # print(frame.item(0, 0, 23))
    # print(frame.item(0, 0, 24))
    # print(frame.item(0, 0, 25))
    # print(frame.item(0, 0, 26))
    # print(frame.item(0, 0, 27))
    # print(frame.item(0, 0, 28))
    # print(frame.item(0,